name: Dummy Core Test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ghdl/synth:beta

    steps:
    - uses: actions/checkout@v2
#     - name: Set up Python 3.8
#       uses: actions/setup-python@v2
#       with:
#         python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd software/cryptotvgen && pip install .
    - name: dummy core test_all
      run: |
        hardware/dummy_lwc/test_all.py
