name = "LWC"
rtl.sources = [
    "LWC_rtl/NIST_LWAPI_pkg.vhd",
    "LWC_rtl/PISO.vhd",
    "LWC_rtl/SIPO.vhd",
    "LWC_rtl/FIFO.vhd",
    "LWC_rtl/PreProcessor.vhd",
    "LWC_rtl/PostProcessor.vhd",
    "LWC_rtl/LWC.vhd",
]
rtl.top = "LWC"

tb.sources = [
    "LWC_tb/LWC_TB.vhd"
]
