name = "LWC_32"

dependencies = [{ uri = "./LWC_common.toml", rtl.pos = 1 }]
rtl.sources = [
    "LWC_config_32.vhd",
    "LWC_rtl/LWC.vhd",
]
rtl.top = "LWC"

tb.sources = [
    "LWC_tb/LWC_TB.vhd"
]
tb.top = "LWC_TB"
