name = "LWC_2Pass_32"

rtl.sources = [
    "LWC_rtl/NIST_LWAPI_pkg.vhd",
    "LWC_rtl/PISO.vhd",
    "LWC_rtl/SIPO.vhd",
    "LWC_rtl/FIFO.vhd",
    "LWC_rtl/PreProcessor.vhd",
    "LWC_rtl/PostProcessor.vhd",
    "LWC_rtl/LWC_2Pass.vhd",
]
rtl.top = "LWC"

tb.sources = [
    "LWC_tb/LWC_TB_2Pass_uut.vhd",
    "LWC_tb/LWC_TB.vhd"
]
tb.top = "LWC_TB"
