# LWC_ROOT variable MUST be set to the the absolute path of the LWC package's TOP directory.
# This is the location where the `lwc.mk` file resides. 
# $(PWD) is the currect working directory, which is assumed to be the location of user design files.
LWC_ROOT = $(PWD)/../../..
HW_DIR = $(LWC_ROOT)/hardware

# Change if `sources_list` file is in a different location
#SOURCE_LIST_FILE := $(CORE_ROOT)/source_list.txt

# MUST include this file
include $(HW_DIR)/lwc.mk
