name = "dummy_lwc_w32_ccw32"
description = "Implementation of the dummy_lwc cipher and hash with W=32 and CCW=32"

[language]
vhdl.standard = "2002"
vhdl.synopsys = false

[rtl]

sources = [
    "src_rtl/v1/design_pkg.vhd",
    "src_rtl/LWC_config_32.vhd",
    "src_rtl/LWC/NIST_LWAPI_pkg.vhd",
    "src_rtl/SPDRam.vhd",
    "src_rtl/CryptoCore.vhd",
    "src_rtl/LWC/data_sipo.vhd",
    "src_rtl/LWC/key_piso.vhd",
    "src_rtl/LWC/data_piso.vhd",
    "src_rtl/LWC/FIFO.vhd",
    "src_rtl/LWC/PreProcessor.vhd",
    "src_rtl/LWC/PostProcessor.vhd",
    "src_rtl/LWC/LWC.vhd",
    # "src_rtl/LWC_wrapper.vhd",
]
top = 'LWC'
clock.port = "clk"

[tb]
top = 'LWC_TB'
sources = ["../LWC_tb/LWC_TB.vhd"]

[tb.generics]
G_FNAME_PDI.file = "KAT/32/pdi.txt"
G_FNAME_SDI.file = "KAT/32/sdi.txt"
G_FNAME_DO.file = "KAT/32/do.txt"
G_TEST_MODE = 1                     # 1: stall both inputs and output
G_MAX_FAILURES = 0
G_TIMEOUT_CYCLES = 1000
G_PDI_STALLS = 7
G_SDI_STALLS = 13
G_DO_STALLS = 21
G_RANDOM_STALL = true              # true
