name = "dummy_lwc_w16_ccw16"
description = "Implementation of the dummy_lwc cipher and hash with W=16 and CCW=16"

[language]
vhdl.standard = "2008"
vhdl.synopsys = false

[rtl]

sources = [
    "src_rtl/v2/design_pkg.vhd",
    "src_rtl/LWC_config_16.vhd",
    "src_rtl/LWC/NIST_LWAPI_pkg.vhd",
    "src_rtl/SPDRam.vhd",
    "src_rtl/CryptoCore.vhd",
    "src_rtl/LWC/data_sipo.vhd",
    "src_rtl/LWC/key_piso.vhd",
    "src_rtl/LWC/data_piso.vhd",
    "src_rtl/LWC/FIFO.vhd",
    "src_rtl/LWC/PreProcessor.vhd",
    "src_rtl/LWC/PostProcessor.vhd",
    "src_rtl/LWC/LWC.vhd",
    # "../LWC_rtl/LWC_wrapper.vhd",
]
top = "LWC"
clock.port = "clk"

[tb]
sources = [
    "src_rtl/v2/design_pkg.vhd",
    "src_rtl/LWC_config_16.vhd",
    "src_rtl/LWC/NIST_LWAPI_pkg.vhd",
    "../LWC_tb/LWC_TB.vhd",
    # "../LWC_tb/LWC_TB_wrapper_conf.vhd",
]
top = "LWC_TB"
uut = 'uut'

[tb.generics]
G_FNAME_PDI.file = "KAT/16/pdi.txt"
G_FNAME_SDI.file = "KAT/16/sdi.txt"
G_FNAME_DO.file = "KAT/16/do.txt"
G_TEST_MODE = 0                     # 1: stall both inputs and output
G_MAX_FAILURES = 0
G_TIMEOUT_CYCLES = 1000
G_PDI_STALLS = 7
G_SDI_STALLS = 13
G_DO_STALLS = 21
G_RANDOM_STALL = false              # true
G_PRERESET_WAIT_NS = 100
G_CLK_PERIOD_PS = 10000
G_INPUT_DELAY_NS = 5

[lwc]
aead.algorithm = "dummy_lwc"
hash.algorithm = "dummy_lwc"

ports.pdi.bit_width = 8
portssdi.bit_width = 8
