name = "dummy_lwc_w8_ccw8"
description = "Implementation of the dummy_lwc cipher and hash with W=8 and CCW=8"

[language]
vhdl.standard = "2002"
vhdl.synopsys = false

[rtl]

sources = [
    "src_rtl/v3/design_pkg.vhd",
    "src_rtl/LWC_config_8.vhd",
    "src_rtl/LWC/NIST_LWAPI_pkg.vhd",
    "src_rtl/SPDRam.vhd",
    "src_rtl/CryptoCore.vhd",
    "src_rtl/LWC/SIPO.vhd",
    "src_rtl/LWC/PISO.vhd",
    "src_rtl/LWC/FIFO.vhd",
    "src_rtl/LWC/PreProcessor.vhd",
    "src_rtl/LWC/PostProcessor.vhd",
    "src_rtl/LWC/LWC.vhd",
]
top = 'LWC'
clock.port = "clk"

[tb]
top = 'LWC_TB'
sources = ["../LWC_tb/LWC_TB.vhd"]

[tb.generics]
G_FNAME_PDI.file = "KAT/8/pdi.txt"
G_FNAME_SDI.file = "KAT/8/sdi.txt"
G_FNAME_DO.file = "KAT/8/do.txt"
G_TEST_MODE = 1                     # stall both inputs and output
G_MAX_FAILURES = 0
G_TIMEOUT_CYCLES = 1000
G_PDI_STALLS = 7
G_SDI_STALLS = 13
G_DO_STALLS = 21
G_RANDOM_STALL = false              # true

[lwc]
aead.algorithm = "dummy_lwc"
hash.algorithm = "dummy_lwc"

ports.pdi.bit_width = 8
portssdi.bit_width = 8
