# LWC_ROOT variable MUST be set to the the path of the LWC package's TOP directory.
# The path can be relative to the current directory where this Makefile resides.
# DO NOT USE $(PWD) as it does not work correctly with the scripts!
LWC_ROOT=../..

# Change if `sources_list` file is in a different location
#SOURCE_LIST := source_list_2.txt


## DON'T CHANGE ANYTHING BELOW THIS LINE ##
# MUST include this file
include $(LWC_ROOT)/hardware/lwc.mk
