[project]
description = "Implementation of the dummy_lwc cipher and hash"
author = "[Patrick Karl](patrick.karl@tum.de)"
url = "https://github.com/GMUCERG/LWC"

[[design]]
name = "dummy_lwc_w32_ccw32"
rtl.sources = [
    "src_rtl/v1/design_pkg.vhd",
    "src_rtl/LWC/NIST_LWAPI_pkg.vhd",
    "src_rtl/LWC/LWC_pkg.vhd",
    "src_rtl/SPDRam.vhd",
    "src_rtl/CryptoCore.vhd",
    "src_rtl/LWC/data_sipo.vhd",
    "src_rtl/LWC/key_piso.vhd",
    "src_rtl/LWC/data_piso.vhd",
    "src_rtl/LWC/fifo.vhd",
    "src_rtl/LWC/PreProcessor.vhd",
    "src_rtl/LWC/PostProcessor.vhd",
    "src_rtl/LWC/LWC.vhd",
    # "src_rtl/LWC/elastic_reg_fifo.vhd",
    # "src_rtl/LWC_wrapper.vhd",
]
rtl.top = 'LWC'
rtl.clock_port = "clk"

tb.top = 'LWC_TB'
tb.sources = ["../LWC_tb/LWC_TB.vhd"]

language.vhdl.standard = "02"
language.vhdl.synopsys = false

[design.tb.generics]
G_FNAME_PDI.file = "KAT/32/pdi.txt"
G_FNAME_SDI.file = "KAT/32/sdi.txt"
G_FNAME_DO.file = "KAT/32/do.txt"
G_TEST_MODE = 0 # stall both inputs and output
G_MAX_FAILURES = 0
G_TIMEOUT_CYCLES = 100

##################################################

[[design]]
name = "dummy_lwc_w32_ccw16"
rtl.sources = [
    "src_rtl/v2/design_pkg.vhd",
    "src_rtl/LWC/NIST_LWAPI_pkg.vhd",
    "src_rtl/LWC/LWC_pkg.vhd",
    "src_rtl/SPDRam.vhd",
    "src_rtl/CryptoCore.vhd",
    "src_rtl/LWC/data_sipo.vhd",
    "src_rtl/LWC/key_piso.vhd",
    "src_rtl/LWC/data_piso.vhd",
    "src_rtl/LWC/fifo.vhd",
    "src_rtl/LWC/PreProcessor.vhd",
    "src_rtl/LWC/PostProcessor.vhd",
    "src_rtl/LWC/LWC.vhd",
]
rtl.top = 'LWC'
rtl.clock_port = "clk"

tb.top = 'LWC_TB'
tb.sources = ["../LWC_tb/LWC_TB.vhd"]

language.vhdl.standard = "08"
language.vhdl.synopsys = false

[design.tb.generics]
G_FNAME_PDI.file = "KAT/32/pdi.txt"
G_FNAME_SDI.file = "KAT/32/sdi.txt"
G_FNAME_DO.file = "KAT/32/do.txt"
G_TEST_MODE = 0
G_MAX_FAILURES = 0

##################################################

[[design]]
name = "dummy_lwc_w32_ccw8"
rtl.sources = [
    "src_rtl/v3/design_pkg.vhd",
    "src_rtl/LWC/NIST_LWAPI_pkg.vhd",
    "src_rtl/LWC/LWC_pkg.vhd",
    "src_rtl/SPDRam.vhd",
    "src_rtl/CryptoCore.vhd",
    "src_rtl/LWC/data_sipo.vhd",
    "src_rtl/LWC/key_piso.vhd",
    "src_rtl/LWC/data_piso.vhd",
    "src_rtl/LWC/fifo.vhd",
    "src_rtl/LWC/PreProcessor.vhd",
    "src_rtl/LWC/PostProcessor.vhd",
    "src_rtl/LWC/LWC.vhd",
]
rtl.top = 'LWC'
rtl.clock_port = "clk"

tb.top = 'LWC_TB'
tb.sources = ["../LWC_tb/LWC_TB.vhd"]

language.vhdl.standard = "08"
language.vhdl.synopsys = false

[design.tb.generics]
G_FNAME_PDI.file = "KAT/32/pdi.txt"
G_FNAME_SDI.file = "KAT/32/sdi.txt"
G_FNAME_DO.file =  "KAT/32/do.txt"
G_TEST_MODE = 0
G_MAX_FAILURES = 0

##################################################

[[design]]
name = "dummy_lwc_w16_ccw16"
rtl.sources = [
    "src_rtl/v2/design_pkg.vhd",
    "src_rtl/NIST_LWAPI_pkg_W16.vhd",
    "src_rtl/LWC/LWC_pkg.vhd",
    "src_rtl/SPDRam.vhd",
    "src_rtl/CryptoCore.vhd",
    "src_rtl/LWC/data_sipo.vhd",
    "src_rtl/LWC/key_piso.vhd",
    "src_rtl/LWC/data_piso.vhd",
    "src_rtl/LWC/fifo.vhd",
    "src_rtl/LWC/PreProcessor.vhd",
    "src_rtl/LWC/PostProcessor.vhd",
    "src_rtl/LWC/LWC.vhd"
]
rtl.top = 'LWC'
rtl.clock_port = "clk"

tb.top = 'LWC_TB'
tb.sources = ["../LWC_tb/LWC_TB.vhd"]

language.vhdl.standard = "08"
language.vhdl.synopsys = false

[design.tb.generics]
G_FNAME_PDI.file = "KAT/16/pdi.txt"
G_FNAME_SDI.file = "KAT/16/sdi.txt"
G_FNAME_DO.file = "KAT/16/do.txt"
G_TEST_MODE = 0
G_MAX_FAILURES = 0

##################################################


[[design]]
name = "dummy_lwc_w8_ccw8"
description = "W=SW=8 CCW=CCSW=8"
rtl.sources = [
    "src_rtl/v3/design_pkg.vhd",
    "src_rtl/NIST_LWAPI_pkg_W8.vhd",
    "src_rtl/LWC/LWC_pkg.vhd",
    "src_rtl/SPDRam.vhd",
    "src_rtl/CryptoCore.vhd",
    "src_rtl/LWC/data_sipo.vhd",
    "src_rtl/LWC/key_piso.vhd",
    "src_rtl/LWC/data_piso.vhd",
    "src_rtl/LWC/fifo.vhd",
    "src_rtl/LWC/PreProcessor.vhd",
    "src_rtl/LWC/PostProcessor.vhd",
    "src_rtl/LWC/LWC.vhd"
]
rtl.top = 'LWC'
rtl.clock_port = "clk"

tb.top = 'LWC_TB'
tb.sources = ["../LWC_tb/LWC_TB.vhd"]

language.vhdl.standard = "02"
language.vhdl.synopsys = false

[design.tb.generics]
G_FNAME_PDI.file = "KAT/8/pdi.txt"
G_FNAME_SDI.file = "KAT/8/sdi.txt"
G_FNAME_DO.file = "KAT/8/do.txt"
G_TEST_MODE = 0
G_MAX_FAILURES = 0

##################################################
##################################################
##################################################
[flows.ghdl_sim]
# ghw = 'dump_ghdl.ghw'
# vcd = 'dump_ghdl.vcd'
# stop_time = '5us'
