name: Main Test

on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: ghdl/setup-ghdl-ci@nightly
      with:
        backend: gcc
    - run: ghdl --version
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade setuptools
        cd software/cryptotvgen && python3 -m pip install --upgrade . && cd ../..
        python3 -m pip install --upgrade git+https://github.com/XedaHQ/xeda.git@dev
    - name: dummy core test_all
      run: |
        cd hardware/dummy_lwc && python3 ./test_all.py
